config/routes.rb
WhatAreYouWearing::Application.routes.draw do
  root to: 'costumes#index'

  match "/costumes/rule" => 'costumes#rule'
  resources :costumes, only: [:index, :show, :create, :destroy] do
    collection do
      get :reset
    end
  end
end

app/models/costume.rb
class Costume < ActiveRecord::Base
  attr_accessible :other, :color, :kind

  validates :kind, presence: true, length: {minimum: 1}, if: :clothers?
  validates :color, presence: true, length: {minimum: 1}, unless: :other?
  validates :other, presence: true, length: {minimum: 1}, unless: :clothers?
  before_save :others, if: :kind_and_color_is_not_chosen

  scope :top, where(kind: 'top')
  scope :bottom, where(kind: 'bottom')
  scope :boots, where(kind: 'boots')
  scope :others, where(kind: 'others')

  def other?
    kind == 'others' || kind == ''
  end

  private

  def others
    self.kind = 'others'
  end

  def kind_and_color_is_not_chosen
    kind == '' && color == ''
  end

  def clothers?
    color != ''
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/costumes_controller.rb
# coding: utf-8
class CostumesController < ApplicationController
  def create
    @costume = Costume.new(params[:costume])
    if @costume.save
      redirect_to @costume
    else
      flash[:error] = '正しく選択してください'
      redirect_to :back
    end
  end

  def show
    @costume = Costume.find(params[:id])
  end

  def index
    @costume = Costume.new
  end

  def destroy
    @costume = Costume.find(params[:id])
    @costume.destroy
    redirect_to costumes_url
  end

  def reset
    Costume.delete_all
    redirect_to costumes_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nth
    Costume.all.count
  end
end

app/views/costumes/index.html.erb
<section>
  <table>
    <tr class="top">
      <th>
        <%= image_tag '/images/top.png', size: '300x155', alt: 'top' %>
      </th>
      <td>
        <% Costume.top.each do |cos| %>
          <%= link_to image_tag("/images/top_#{cos.color}.jpg", size: '120x95', alt: 'top'), cos %>
        <% end %>
      </td>
    </tr>

    <tr class="bottom">
      <th>
        <%= image_tag '/images/bottom.png', size: '300x155', alt: 'bottom' %>
      </th>
      <td>
        <% Costume.bottom.each do |cos| %>
          <%= link_to image_tag("/images/bottom_#{cos.color}.jpg", size: '120x95', alt: 'bottom'), cos %>
        <% end %>
      </td>
    </tr>

    <tr class="boots">
      <th>
        <%= image_tag '/images/boots.png', size: '300x155', alt: 'boots' %>
      </th>
      <td>
        <% Costume.boots.each do |cos| %>
          <%= link_to image_tag("/images/boots_#{cos.color}.jpg", size: '120x95', alt: 'boots'), cos %>
        <% end %>
      </td>
    </tr>

    <tr class="others">
      <th>
        <%= image_tag '/images/others.png', size: '300x155', alt: 'others' %>
      </th>
      <td>
        <% Costume.others.each do |cos| %>
          <%= link_to image_tag("/images/others_#{cos.other}.jpg", size: '120x95', alt: 'others'), cos %>
        <% end %>
      </td>
    </tr>
  </table>
</section>

<section>
  <div class="form">
    <%= form_for @costume do |f| %>
      <%= f.select :kind, [['トップス', 'top'], ['ボトムス','bottom'], ['ひざ下','boots']], prompt: 'clothes' %>
      <%= f.select :color, [['赤', 'red'], ['茶', 'brown'], ['青','blue'], ['黄','yellow'], ['緑', 'green'], ['黒','black'], ['灰','gray'], ['白', 'white'], ['アロハ', 'aloha'], ['沖縄', 'okinawa']], prompt: 'color' %>
      <%= f.select :other, [['時計', 'watch'], ['指輪','ring'], ['イヤリング','earrings'], ['スマフォ', 'phone'], ['メガネ','glasses'], ['32歳以上','age32over']], prompt: 'others' %>
      <%= f.submit 'Submit', class: "btn btn-primary submit" %>
    <% end %>
  </div>
</section>

app/views/costumes/rule.html.erb
<section class="rule">
  <h1 class="title">ルール説明 「ふたりでビンゴ！協力してね♪」</h1>
  <ol>
    <li>2人1組のチームを作って下さい</li>
    <li>2種類のくじを引きます。その2つのクジの組み合わせを見て、</br>パートナーが身につけているものをお互いにチェックして下さい</li>
    <li>パートナーが身につけているものをが、くじと同じだったら1ポイントゲット</br>ポイントゲットするたびに紙に正の字を書いて下さい</li>
    <li>何回かクジを引きます。</br>2人の合計ポイントが高いと豪華賞品がもらえる!!かも??</br>どんなクジが出るかはお楽しみ♪</li>
  </ol>
</section>
<span class="btn btn-large reset"><%= link_to 'Game Reset', {controller: 'costumes', action: 'reset'}, {confirm: 'リセットしますか？'} %></span>

app/views/costumes/show.html.erb
<div class="original">
  <%= link_to image_tag("/images/#{@costume.kind}_#{@costume.color}.jpg", size: '100%', alt: 'top'), costumes_path unless @costume.other? %>
  <%= link_to image_tag("/images/#{@costume.kind}_#{@costume.other}.jpg", size: '962x722', alt: 'top'), costumes_path if @costume.other? %>
</div>

<%= link_to 'Destroy', @costume, confirm: '本当に削除しますか？', method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatAreYouWearing?</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= stylesheet_link_tag    "contents", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <div class="brand">
            <% if request.path == '/costumes' %>
              <span><%= link_to 'WhatAreYouWearing?', costumes_rule_path %></span>
            <% else %>
              <span><%= link_to 'WhatAreYouWearing?', costumes_path %></span>
            <% end %>
          </div>
          <div class="nth pull-right">
          <span><%= "#{nth} 回目" %></span>
          </div>
        </div>
      </div>
    </header>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
      <div class="flash">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class:"alert alert-#{key}") %>
        <% end %>
      </div>
    </div>
  </body>
</html>